apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: docker-cluster.example.com-nodes
  namespace: kubernetes-docker-cluster-example-com
spec:
  template:
    spec: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: docker-cluster.example.com-nodes
  namespace: kubernetes-docker-cluster-example-com
spec:
  clusterName: docker-cluster
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: docker-cluster.example.com-nodes
          namespace: kubernetes-docker-cluster-example-com
      clusterName: docker-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: docker-cluster.example.com-nodes
        namespace: kubernetes-docker-cluster-example-com
      version: v1.22.0
