name: Go

on:
  push:
    branches:
    - main
    - feat/create-api
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install dependencies
      run: sudo apt update && sudo apt install make -y

    - name: Run lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: latest  

    - name: Run tests
      run: make test
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${GITHUB_REPOSITORY}:latest
          ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}
        
