name: Go

on:
  push:
    branches:
    - main
    - feat/create-api
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install dependencies
      run: sudo apt update && sudo apt install make -y

    - name: Build
      run: make build
